"""fix position

Revision ID: 483508ccf69a
Revises: 16920d107188
Create Date: 2023-04-12 12:57:37.268092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '483508ccf69a'
down_revision = '16920d107188'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###