"""Fix date

Revision ID: e06fc13efc99
Revises: b4c763b0c2ef
Create Date: 2023-04-06 12:40:14.932074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e06fc13efc99'
down_revision = 'b4c763b0c2ef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###